version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn -w 4 -b 0.0.0.0:8080 main:app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    links:
      - database
    depends_on:
      - database
    networks:
      - default
  database:
    image: mongo:latest
    env_file:
      - ./.env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-volume/log:/var/log/mongodb/
    ports:
      - "27017:27017"
    networks:
      - default
volumes:
  mongo-volume:
    driver: local
