version: '3.8'

services:

  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - ./mongo-volume:/data/db
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "sh"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - ./:/app
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
    networks:
      - default
networks:
  default:
    name: localdev
volumes:
  mongo-volume:
    driver: local
